version: "3.8"
services:
  redis: 
    image: redis:latest
    ports: 
        - "6363:6379"
    networks: 
        - fastfoodnet
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
    hostname: redis
    mem_limit: 250m
    cpus: 0.5
  backend:
    image: abiwardani/jenkins-api:master
    ports:
      - 2020-2021:2000
    volumes:
      - ./backendlog:/user/backend
    environment: 
      - DB_USER=
      - MODE=
      - DB_DATABASE=
      - DB_HOST=
      - DB_PORT=
      - DB_PASS=
      - JWT_KEYS=
      - CLOUD_KEY=
      - CLOUD_SECRET=
      - CLOUD_NAME=
      - REDIS_HOST=
      - REDIS_PORT=
    networks:
      - fastfoodnet
    depends_on:
      - redis
    mem_limit: 250m
    cpus: 0.5
    scale: '2'
    
networks:
  fastfoodnet:
